apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-test-service
  labels:
    app: redis-test-service
    type: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-test-service
  template:
    metadata:
      labels:
        type: spring-boot-app
        app: redis-test-service
    spec:
      containers:
        - name: redis-test-service
          image: docker.io/mcintoshj/redis-test-service:0.0.6-SNAPSHOT-amd
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
          volumeMounts:
          - mountPath: /opt/application/config/
            name: test-service-config
      volumes:
        - name: test-service-config
          configMap:
            name: test-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-service
data:
  application.yaml: |
    redis:
      checker:
        driver: redisson
    spring:
      redis:
        redisson:
          config: |
            sentinelServersConfig:
              idleConnectionTimeout: 30000
              connectTimeout: 1000
              timeout: 5000
              retryAttempts: 3
              retryInterval: 1500
              failedSlaveReconnectionInterval: 3000
              failedSlaveNodeDetector: !<org.redisson.client.FailedConnectionDetector> {}
              password: null
              subscriptionsPerConnection: 5
              clientName: null
              loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
              subscriptionConnectionMinimumIdleSize: 1
              subscriptionConnectionPoolSize: 50
              slaveConnectionMinimumIdleSize: 1
              slaveConnectionPoolSize: 64
              masterConnectionMinimumIdleSize: 1
              masterConnectionPoolSize: 64
              readMode: "MASTER"
              subscriptionMode: "MASTER"
              sentinelAddresses:
                - "redis://127.0.0.1:26379"
                - "redis://127.0.0.1:26389"
              masterName: "mymaster"
              database: 0
            threads: 16
            nettyThreads: 32
            codec: !<org.redisson.codec.Kryo5Codec> {}
            transportMode: "NIO"
      data:
        redis:
          sentinel:
            master: harness-redis
            nodes:
            - redis-sentinel-harness-announce-0:26379
            - redis-sentinel-harness-announce-1:26379
            - redis-sentinel-harness-announce-2:26379
